### ISSUE TITLE
2021-04-10 18:49:03: Error: 未能读取数据，因为它的格式不正确。

### ISSUE THREAD

**Issue by oniyou** [wickenico/btc-usd-course.js#2]
2021-04-10 18:49:03: Error: 未能读取数据，因为它的格式不正确。

![9FD7698C-198F-4BC1-ADEC-70B987E92286](https://user-images.githubusercontent.com/39154346/114267365-afe29500-9a2d-11eb-8e17-51b9453bb4de.png)

**Comment by oniyou** [comment]
Just now, it is running okay, I’m confused...

**Comment by oniyou** [comment]
And this time, it report failures again...

![Uploading 2FE2A1D0-49AE-41E6-82A8-2704C08DB5A5.png…]()

**Comment by oniyou** [comment]
You can see everytime it runs different results

**Comment by oniyou** [comment]
I have fixed it by myself, thank you...

**Comment by wickenico** [comment]
if it is something for a general fix just let me know what you've done :)

**Comment by oniyou** [comment]
> if it is something for a general fix just let me know what you've done :)

Maybe it caused by my unstable network, I don’t know,  cuz I am in China.
